import type { NextPage } from "next";
import Head from "next/head";
import styled from "styled-components";
import { css } from "@emotion/react";
import { styles } from "../styles/home";

const Foo = styled.a`
  color: crimson;
  border-bottom: dotted 1px;
`;

const testStyle = css`
  background: #f3f3f3;
  font-size: 14px;
  padding: 12px;
`;

const Home: NextPage = () => {
  return (
    <div
      css={css`
        padding: 40px;
      `}
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
          <span> with Emotion</span>
        </h1>
        <Foo>Styled Components</Foo>
        <div css={testStyle}>
          <p>こんにちは、pタグさん。</p>
        </div>
        <button css={styles.sampleButton}>Button Label</button>

        <p>
          Get started by editing <code>pages/index.tsx</code>
        </p>
      </main>
    </div>
  );
};

export default Home;
